API Documentation: Ad Rendering Service
Overview
The Ad Rendering Service is a JavaScript-based API that allows clients to dynamically load and render advertisements on their websites. This service is implemented using a GoLang backend and leverages JavaScript for client-side functionality.

API Endpoint
Endpoint: /ad.js
Method: GET
How It Works
The Ad Rendering Service works by serving a JavaScript script tag that clients can include on their websites. This script tag loads and executes the necessary JavaScript code to fetch and render ads.

Script Tag
The script tag's src attribute points to the /ad.js endpoint of the API. Upon loading, the script is dynamically generated by the API, which includes client-specific configuration and dynamic data. The API parses a JavaScript template, injecting data such as the currently executing script ID and ad ID to ensure unique identification.

Dynamic Data Injection
The following dynamic data is inserted into the JavaScript template:

Executing Script ID: To uniquely identify the currently executing script.
Ad ID: To uniquely identify the HTML div element where the ad will be rendered.
Ad API URL: The URL used to fetch the ad, which is also injected into the JavaScript template.
Execution Flow
The client embeds the script tag on their website, referencing the /ad.js endpoint.
The browser loads the script tag and executes the JavaScript code.
The JavaScript code retrieves the currently executing script tag using document.getCurrentScript().
Upon the DOMContentLoaded event, the code dynamically creates a script tag to load the jQuery library.
The jQuery script tag is inserted into the <head> element of the HTML page to ensure jQuery is available.
The Ad Rendering Service's script creates an HTML <div> element just below the currently executing script.
The jQuery onload event handler ensures that the jQuery library is fully loaded.
Once jQuery is ready, the code uses it to fetch remote HTML ad content and render it within the previously created <div> element.
Usage Example
To use the Ad Rendering Service, include the following script tag in your HTML:

html
Copy code
<script src="/ad.js"></script>
Ensure that this tag is placed in the HTML where you want the ad to be rendered.

Security Considerations
Ensure that you trust the dynamic data being injected into the JavaScript template to prevent security vulnerabilities such as Cross-Site Scripting (XSS).
Consider implementing measures to restrict access to the /ad.js endpoint to prevent misuse.
Conclusion
The Ad Rendering Service simplifies the process of including dynamic ads on your website. By embedding the provided script tag and referencing the /ad.js endpoint, you can seamlessly load and render advertisements.

For more information or assistance, please contact our support team.

Note: This documentation is a general template and should be customized to fit the specific implementation and requirements of your API.
